# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
r_check_args: "--no-vignettes"

addons:
  apt:
    packages:
      - libnetcdf-dev
      - libudunits2-dev
      - netcdf-bin
      - libnetcdf-dev
      - libxml2
      - libxml2-dev
      - libssl-dev
